apiVersion: v1
kind: Service
metadata:
  name: account-service
  annotations: 
    alb.ingress.kubernetes.io/healthcheck-path: /account
spec:
  type: NodePort
  selector:
    app: account
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort