apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  annotations: 
    alb.ingress.kubernetes.io/healthcheck-path: /inventory
spec:
  type: NodePort
  selector:
    app: inventory
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80