apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  annotations: 
    alb.ingress.kubernetes.io/healthcheck-path: /shipping
spec:
  type: NodePort
  selector:
    app: shipping
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80