apiVersion: v1
kind: Service
metadata:
  name: storefront-service
  annotations: 
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: NodePort
  selector:
    app: storefront
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80