apiVersion: v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels: 
    name: postgres-deploy
    app: demo-voiting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: demo-voiting-app

  template:
    metadata:
      name: postgres-pod
      labels: 
        name: postgres-pod
        app: demo-voiting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"