apiVersion: v1
kind: Service
metadata:
  name: voiting-service
  labels:
    name: voiting-service
    app: demo-voiting-app
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    name: voiting-app-pod
    app: demo-voiting-app