apiVersion: v1
kind: Deployment
metadata:
  name: worker-deploy
  labels: 
    name: worker-deploy
    app: demo-voiting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-app-pod
      app: demo-voiting-app

  template:
    metadata:
      name: worker-app-pod
      labels: 
        name: worker-app-pod
        app: demo-voiting-app
    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1