plugin: aws_ec2
regions:
  - "us-east-1"
keyed_groups:
  - key: tags.Name
    prefix: tag
  - prefix: arch
    key: architecture
  - prefix: tag
    key: tags
  - prefix: region
    key: placement.region
  - key: tags.Name
    separator: ''
  - prefix: instance_type
    key: instance_type
filters:
  instance-state-name : running
compose:
  ansible_host: public_ip_address
  foo: private_ip_address
  boo: instance_id
  key: key_name