    #!/bin/bash
    ### Constants ###
    CON_DAYS=.0000000115741
    CON_HOURS=.000000277778
    CON_MINUTES=.000066667
    CON_SECONDS=.001

    ### Variables ###
    INPUT="$1"

    cat $INPUT | awk -v CON_HOURS=$CON_HOURS -v CON_MINUTES=$CON_MINUTES -v CON_SECONDS=$CON_SECONDS -v CON_DAYS=$CON_DAYS '
        { $1=substr($0,0,10) }
        { MILLISECONDS = $1 }
        { DAYS = int(MILLISECONDS * CON_DAYS) }
        { MILLISECONDS = MILLISECONDS - int( DAYS / CON_DAYS ) }
        { HOURS = int(MILLISECONDS * CON_HOURS) }
        { MILLISECONDS = MILLISECONDS - int(HOURS / CON_HOURS) }
        { MINUTES = int(MILLISECONDS * CON_MINUTES) }
        { MILLISECONDS = MILLISECONDS - int(MINUTES / CON_MINUTES) }
        { SECONDS = int(MILLISECONDS * CON_SECONDS) }
        { MILLISECONDS = MILLISECONDS - int( SECONDS / CON_SECONDS ) }
        { $1 = DAYS":"HOURS":"MINUTES":"SECONDS":"MILLISECONDS"ms" }
        {print}'
    exit