AWSTemplateFormatVersion: 2010-09-09

Description: |
  Personal Website with Cloudformation 

Parameters:
  myVPC:
    Description: Select your VPC
    Type: AWS::EC2::VPC::Id

  myKP:
    Description: Select your Key
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  Certificatewebsite:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: "harungur.com" # Required
      ValidationMethod: "DNS"


LogicalID:
  Type: AWS::CertificateManager::Certificate
  Properties:
    CertificateAuthorityArn: "String"
    CertificateTransparencyLoggingPreference: "String"
    DomainName: "harungur.com" # Required
    DomainValidationOptions:
      DomainValidationOptions
    SubjectAlternativeNames:
      SubjectAlternativeNames
    Tags:
      Tags
    ValidationMethod: "DNS"


ACMCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: example.com
      DomainValidationOptions:
            - DomainName: www.example.com
              HostedZoneId: ZZZHHHHWWWWAAA
      ValidationMethod: DNS 



##Çalıştırıldı