apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    environment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
        


        # # kubectl get deployment
        # # kubectl get pods -o wide
        # # kubectl delete deployment nginx-rs
        # # kubectl delete - f deployment.yaml



kubectl get deploy,rs,po -l app=container-info ## ilgili etiketteki deployment replicaset ve podları listeler

kubectl get namespace