apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:    ## Specificatin of pod
  containers:
  - name: nginx
    image: nginx:1.14.2 ## Search it  or creat it in dockerhub
    ports:
    - containerPort: 80 ## Port