apiVersion: v1
kind: Pod
metadata:
  name: postgres-app-pod
  labels: 
    name: postgres-app-pod
    app: demo-voting-app-pod
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"