apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels: 
    name: redis-app-pod
    app: demo-voting-app-pod
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379